# DO NOT EDIT THIS FILE!
#
# Python module Program_Hangman generated by omniidl

import omniORB
omniORB.updateModule("Program_Hangman")

# ** 1. Stub files contributing to this module
import hangman_idl

# ** 2. Sub-modules

# ** 3. End
